# -*- coding: utf-8 -*-

"""
/***************************************************************************
 CatGrowing
                                 A QGIS plugin
 Region-growing algorithm for spatial analysis using categorical raster and vector data.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-01-08
        copyright            : (C) 2025 Consejo Superior de Investigaciones Científicas (CSIC), Estación Experimental de Zonas Áridas (EEZA)
        email                : arranca@eeza.csic.es
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 3 of the License, or     *
 *   any later version.                                                    *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Developed by Alberto Ruiz-Rancaño, under contract by Gabriel del Barrio Escribano (EEZA - CSIC)'
__date__ = '2024-01-08'
__copyright__ = '(C) 2025 Consejo Superior de Investigaciones Científicas (CSIC), Estación Experimental de Zonas Áridas (EEZA)'



# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Cover class from file Cover.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .cat_growing import CatGrowingPlugin
    return CatGrowingPlugin()
